apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailout.fullname" . }}-config
data:
  {{- if .Values.config.aliases }}
  aliases: |
    {{- .Values.config.aliases | toJson | nindent 4 }}
  {{- end }}
  {{- if .Values.config.caBundle }}
  ca-bundle.trust.crt: |
    {{- .Values.config.caBundle | nindent 4 }}
  {{- end }}
